name: Déploiement GitHub Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
  environment:
      name: github-pages
  steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Upload des fichiers existants
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./index.html

      - name: Déployer sur GitHub Pages
        uses: actions/deploy-pages@v4
